vimをnanoに変更
traP-jp/pg-basic pull request #15
Opened 2024-04-30 13:43 UTC by comavius

2024-04-30 14:21 UTC, Takeno-hito requested changes
Must; index.md のところ変えてください〜

2024-05-01 04:02 UTC, comavius commented
修正しました

2024-05-01 04:12 UTC, Takeno-hito approved these changes, later dismissed

2024-05-01 04:12 UTC, Takeno-hito approved these changes

2024-05-01 04:12 UTC, merged