Chapter 8
traP-jp/pg-basic pull request #6
Opened 2024-04-08 15:25 UTC by comavius

2024-04-09 13:57 UTC, Takeno-hito requested changes
3点チェックお願いします！

2024-04-09 13:57 UTC, Takeno-hito commented on docs/.vitepress/config.ts
> +                items: [
ここに計算量とオーダーのページ入れちゃって大丈夫です！

2024-04-09 13:57 UTC, Takeno-hito commented on docs/text/chapter-8/complexity.md
> +$\exists C \forall, n \in \mathbb{N}_{+}, \frac{f(x)}{g(x)} \leq C$
なんかこの式変じゃないです？ n 使われてなかったり

2024-04-09 13:57 UTC, Takeno-hito commented on docs/text/chapter-8/complexity.md
> +
具体的に多項式を1つ以上並べて、それぞれのオーダーを書いて上げると優しいかもです $(4n+2)^4$ 回は $n^4$ オーダーだよ、みたいな

2024-04-09 13:57 UTC, Takeno-hito commented on docs/text/chapter-8/complexity.md
> +例えば、`std::vector<int>`の最大の要素を得る関数のオーダーは$O(n)$となる。
> 要素の数 $n$ に対し

がほしいかも

2024-04-10 08:52 UTC, comavius commented on docs/text/chapter-8/complexity.md
> +$\exists C \forall, n \in \mathbb{N}_{+}, \frac{f(x)}{g(x)} \leq C$
xじゃなくてnでした

2024-04-13 10:42 UTC, Takeno-hito approved these changes
LGTM

2024-04-13 10:42 UTC, merged